### PR TITLE
 #49 - add anna info

### PR DESCRIPTION
**Pull request by filfreire**
+ minor fixes to daniel info

speakers_001

speakers_002

speakers_003

speakers_005

/cc @FabioCB @filipemcarvalho @nmatos @deepblueness

### CODE REVIEW

**Comment by FabioCB** [comment]
this may impact the schedule. Didi you check it? @filfreire

**Comment by filfreire** [comment]
@FabioCB 

screen shot 2018-04-13 at 08 49 29

tranquilo 😄 

we can go ahead and merge for now

**Comment by filfreire** [comment]
@FabioCB @filipemcarvalho we should merge this PR. Regarding the schedule, I created issue #55 to follow up and remove for now the speakers from schedule

**Comment by filfreire** [comment]
(closed PR by mistake, re-opened it)

**Pull request merged**
